import { useState } from 'react'
import { cn } from '@/lib/utils'

// The 3D graph viewers are self-contained HTML (Three.js) generated by
// os/lightrag-server/{code_graph_3d,knowledge_graph_3d}.py with --embed and
// served from public/graphs/. We embed them in an iframe so PulseOS supplies
// the chrome (nav + this header) while the viewer keeps its own controls
// (label modes, palette, bloom, orbit).
const GRAPHS = {
  code: {
    src: '/graphs/code-graph-3d.html',
    label: 'Code Graph',
    desc: 'The dashboard module-dependency constellation — nodes are files, edges are imports.',
  },
  knowledge: {
    src: '/graphs/knowledge-graph-3d.html',
    label: 'Knowledge Graph',
    desc: 'The LightRAG entity graph — concepts as stars, relations as particle streams.',
  },
  temple: {
    src: '/graphs/temple.html',
    label: 'Temple',
    desc: 'The knowledge graph as a 3D temple — entities as deities on concentric rings.',
  },
} as const

type Kind = keyof typeof GRAPHS

export function GraphScreen() {
  const [kind, setKind] = useState<Kind>('code')
  const active = GRAPHS[kind]

  return (
    <div className="flex h-full flex-col">
      <header className="flex flex-wrap items-center justify-between gap-3 border-b border-primary-200 bg-white px-4 py-3 dark:border-gray-700 dark:bg-gray-900">
        <div className="min-w-0">
          <h1 className="text-sm font-semibold text-ink">Knowledge Graph</h1>
          <p className="truncate text-xs text-primary-500">{active.desc}</p>
        </div>
        <div className="inline-flex shrink-0 rounded-xl border border-primary-200 bg-primary-50 p-1 dark:border-gray-700 dark:bg-gray-800">
          {(Object.keys(GRAPHS) as Array<Kind>).map((k) => (
            <button
              key={k}
              type="button"
              onClick={() => setKind(k)}
              className={cn(
                'rounded-lg px-3 py-1.5 text-xs font-medium transition-colors',
                kind === k
                  ? 'bg-accent-500 text-white shadow-sm'
                  : 'text-primary-600 hover:text-ink',
              )}
            >
              {GRAPHS[k].label}
            </button>
          ))}
        </div>
      </header>

      <div className="relative flex-1 bg-[#070a11]">
        {/* key forces a fresh iframe on toggle so the WebGL scene re-inits cleanly */}
        <iframe
          key={kind}
          src={active.src}
          title={active.label}
          className="absolute inset-0 h-full w-full border-0"
          loading="lazy"
        />
      </div>
    </div>
  )
}
